from enum import Enum

class GameScreen(Enum):
    MAIN = "main"
    TRAINING = "training"
    INSPIRATION = "inspiration"
    EVENT = "event"
    RACE = "race"
    RACE_SELECT = "race_select"
    INSUFFICIENT_FANS = "insufficient_fans"
    SCHEDULED_RACE_POPUP = "scheduled_race_popup"
    RACE_RESULT = "race_result"
    STRATEGY = "strategy"
    UNITY = "unity"
    CAREER_COMPLETE = "career_complete"
    SKILL_SELECT = "skill_select"
    RECREATION = "recreation"
    UNKNOWN = "unknown"

class Action(Enum):
    RACE = "race"
    INFIRMARY = "infirmary"
    RAINBOW_TRAINING = "rainbow_training"
    REST = "rest"
    RECREATION = "recreation"
    TRAINING = "training"
    UNITY_CUP = "unity_cup"
    CLAW_MACHINE = "claw_machine"
    SKIP = "skip"
    COMPLETE = "complete"